# Climate Risk Disclosure Scrapping
This webscrapping tool is developed to download data from the Climate Reporting Entity (CRE) Search Hub. 

```
In recognition of the ongoing impact that climate change has on New Zealand the Government introduced a requirement for large entities to prepare and lodge annual climate-related disclosures (climate statements). These entities are called Climate Reporting Entities (CREs) under the Financial Markets Conduct Act 2013.  

The aim of requiring CREs to consider and report on climate-related risks and opportunities is to encourage a transition to a low-emissions future.

CREs are required to lodge climate statements or exemption notices with the Registrar of Financial Service Providers within 4 months after the balance date of the entity. CREs with a balance date of 31 December 2023 will be the first to file their climate statements which are due by 30 April 2024.

Which entities are Climate Reporting Entities (CREs)
Around 200 entities in New Zealand will be required to prepare and lodge climate statements or exemption notices. CREs are a subset of FMC reporting entities, and include: 
 - Large registered banks, credit unions, and building societies. Those with total assets of more than $1 billion. 
 - Large managers of registered investment schemes (other than restricted schemes). Those with greater than $1 billion in total assets under management. 
 - Large licensed insurers. Those with greater than $1 billion in total assets or annual gross premium income greater than $250 million. 
 - Large listed issuers of quoted equity securities or quoted debt securities. An equity issuer is large if the market price or fair value of all of its equity securities exceeds $60 million and a debt issuer is large if the face value of its quoted debt exceeds $60 million. Issuers listed on growth markets are excluded from the climate reporting entity definition. 
 
The thresholds for each entity are calculated as at the balance date of their 2 preceding accounting periods. These thresholds will be amended from time to time to reflect the movements in the consumers price index.
```
The CRE search hub is this link: https://crd-app.companiesoffice.govt.nz/dashboard/

```
From 1 January 2024 CREs are required to prepare climate statements and lodge them on this register. To begin with, the register only includes CREs with a reporting period up to June 2024. We'll add the remaining CREs in due course.

```

In [1]:
!pip install selenium==3.141.0
!pip install bs4
!pip install webdriver_manager

Requirement already satisfied: selenium==3.141.0 in c:\users\quyenn\appdata\local\anaconda3\lib\site-packages (3.141.0)
Requirement already satisfied: urllib3 in c:\users\quyenn\appdata\local\anaconda3\lib\site-packages (from selenium==3.141.0) (1.26.16)
Requirement already satisfied: bs4 in c:\users\quyenn\appdata\local\anaconda3\lib\site-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in c:\users\quyenn\appdata\local\anaconda3\lib\site-packages (from bs4) (4.12.2)
Requirement already satisfied: soupsieve>1.2 in c:\users\quyenn\appdata\local\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.4)
Requirement already satisfied: webdriver_manager in c:\users\quyenn\appdata\local\anaconda3\lib\site-packages (4.0.1)
Requirement already satisfied: requests in c:\users\quyenn\appdata\local\anaconda3\lib\site-packages (from webdriver_manager) (2.31.0)
Requirement already satisfied: python-dotenv in c:\users\quyenn\appdata\local\anaconda3\lib\site-packages (from webdriver_manager) (1.0.1)
Requirement already satisfied: packaging in c:\users\quyenn\appdata\local\anaconda3\lib\site-packages (from webdriver_manager) (23.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\quyenn\appdata\local\anaconda3\lib\site-packages (from requests->webdriver_manager) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\quyenn\appdata\local\anaconda3\lib\site-packages (from requests->webdriver_manager) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\quyenn\appdata\local\anaconda3\lib\site-packages (from requests->webdriver_manager) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\quyenn\appdata\local\anaconda3\lib\site-packages (from requests->webdriver_manager) (2023.7.22)

In [9]:
## import the necessary packages which we are going to use here. 
import selenium
from selenium import webdriver 
from selenium.webdriver.chrome.service import Service as ChromeService 
from webdriver_manager.chrome import ChromeDriverManager 
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
import os
import pandas as pd 
import numpy as np
from bs4 import BeautifulSoup
import ast
import time 
from datetime import date

In [5]:
selenium.__version__

'3.141.0'

In [3]:
## Edit accordingly to the file path where an instance of the classes are existing
os.chdir(path=r'C:\Users\QuyenN\Offline work\1.GNS\5-Climate risk disclosure\Classes')
import WebScrapeClass
import TableBuilderClass
import TableTidyandSaveClass

In [14]:
folder = 'C:/Users/QuyenN/Offline work/1.GNS/5-Climate risk disclosure/Classes/'
# Define Chrome options
options = webdriver.ChromeOptions() 
options.headless = True 
options.add_argument("--start-maximized")
options.add_argument("--headless")  # Uncomment this line if you want to run Chrome in headless mode

# Specify the path to the Chrome driver executable
#cService = ChromeService(executable_path= "C:/Users/QuyenN/Offline work/1.GNS/5-Climate risk disclosure/Classes/chromedriver.exe")
driver = webdriver.Chrome(executable_path= "C:/Users/QuyenN/Offline work/1.GNS/5-Climate risk disclosure/Classes/chromedriver.exe")

The first step is to download the list of all entities

In [7]:
## This URL represents the link to CRD hub.  
link= 'https://crd-app.companiesoffice.govt.nz/dashboard/'
# open the browser to activate the process using the URL defined 
driver.get(link)
# extract  data 
table_final = pd.DataFrame()
# Loop through pages 1 to 16
for page_num in range(1, 17):
    # Scroll down to reveal hidden pagination buttons
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    
    # Find the button with data-page attribute
    button_with_data_page = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.CSS_SELECTOR, f'a[data-page="{page_num}"]'))
    )
    # Click the button
    button_with_data_page.click()
    
    # Wait for the table to become visible
    table = WebDriverWait(driver, 10).until(
        EC.visibility_of_element_located((By.CSS_SELECTOR, '#mainContent > div.entitylist > div > div.view-grid.table-responsive.has-pagination > table'))
    )

    # Do something with the table (for demonstration, print its HTML)
    print(f"Table on Page {page_num}:")
    print(table.text)
    
    # Get the table HTML
    table_html = table.get_attribute("outerHTML")
    
    
    #Extract table data
    # Parse the HTML table content with BeautifulSoup
    soup = BeautifulSoup(table_html, 'html.parser')

    # Extract table rows
    rows = soup.find_all('tr')

    # Initialize lists to store table data and associated links
    table_data = []

    # Loop through table rows
    for row in rows:
        # Extract table cells (columns)
        cells = row.find_all(['th', 'td'])
        row_data = []
        for cell in cells:
            # Extract text from cell
            cell_text = cell.get_text(strip=True)
            row_data.append(cell_text)
        links = []
        # Check if cell contains a link
        link = cell.find('a')
        if link:
            # Extract link URL
            link_url = link.get('href')
            links.append(link_url)

        # Remove duplicates using set
        unique_href_values = set(links)

        # Filter out only the elements starting with '/dashboard/reportingentity/?id='
        filtered_href_values = [href for href in unique_href_values if href.startswith('/dashboard/reportingentity/?id=')]

        row_data.append(filtered_href_values)
        # Append row data to table data
        table_data.append(row_data)

    # Convert table data to DataFrame
    table_df = pd.DataFrame(table_data)

    # After obtaining the table, you can perform any further actions required
    table_final = pd.concat([table_final, table_df], ignore_index=True)

Table on Page 1:
CRE Name
. sort ascending
Reporting Entity Status
. sort descending
NZBN
. sort descending
Actions
AA INSURANCE LIMITED Registered 9429040865966
AFT PHARMACEUTICALS LIMITED Registered 9429038010415
AIA NEW ZEALAND LIMITED Registered 9429039580948
AIR NEW ZEALAND LIMITED Registered 9429040402543
AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED Registered 9429038259210
ANZ INVESTMENT SERVICES (NEW ZEALAND) LIMITED Registered 9429039496881
ANZ NEW ZEALAND INVESTMENTS LIMITED Registered 9429039355140
ARBORGEN HOLDINGS LIMITED Registered 9429037034740
ARGOSY PROPERTY LIMITED Registered 9429030890039
ARVIDA GROUP LIMITED Registered 9429041061350
Table on Page 2:
CRE Name
. sort ascending
Reporting Entity Status
. sort descending
NZBN
. sort descending
Actions
ASB BANK LIMITED Registered 9429039435743
ASB GROUP INVESTMENTS LIMITED Registered 9429039025791
ASSET PLUS LIMITED Registered 9429031430098
ASTERON LIFE LIMITED Registered 9429040905464
AUCKLAND COUNCIL Registered 9429000034753
AUCKLAND INTERNATIONAL AIRPORT LIMITED Registered 9429039490162
AUSTRALIAN FOUNDATION INVESTMENT COMPANY LIMITED Registered 9429038280597
BANK OF CHINA (NEW ZEALAND) LIMITED Registered 9429041280874
BANK OF CHINA LIMITED Registered 9429046706850
BARRAMUNDI LIMITED Registered 9429033885575
Table on Page 3:
CRE Name
. sort ascending
Reporting Entity Status
. sort descending
NZBN
. sort descending
Actions
BNZ INVESTMENT SERVICES LIMITED Registered 9429032532593
BOOSTER INVESTMENT MANAGEMENT LIMITED Registered 9429037597320
BRISCOE GROUP LIMITED Registered 9429039267313
BT FUNDS MANAGEMENT (NZ) LIMITED Registered 9429039285126
CDL INVESTMENTS NEW ZEALAND LIMITED Registered 9429039924230
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED Registered 9429030734937
CHANNEL INFRASTRUCTURE NZ LIMITED Registered 9429040663333
CHINA CONSTRUCTION BANK (NEW ZEALAND) LIMITED Registered 9429041075890
CHINA CONSTRUCTION BANK CORPORATION Registered 9429046559289
CHORUS LIMITED Registered 9429031035040
Table on Page 4:
CRE Name
. sort ascending
Reporting Entity Status
. sort descending
NZBN
. sort descending
Actions
CHRISTCHURCH CITY HOLDINGS LIMITED Registered 9429038759475
CHRISTCHURCH INTERNATIONAL AIRPORT LIMITED Registered 9429039502940
CHUBB LIFE INSURANCE NEW ZEALAND LIMITED Registered 9429040894492
CITIBANK, N.A. Registered 9429039497765
COMMONWEALTH BANK OF AUSTRALIA Registered 9429037206192
COMVITA LIMITED Registered 9429040077536
CONTACT ENERGY LIMITED Registered 9429038549977
COOPERATIEVE RABOBANK U.A. Registered 9429038354397
DELEGAT GROUP LIMITED Registered 9429039055422
EBOS GROUP LIMITED Registered 9429031998840
Table on Page 5:
CRE Name
. sort ascending
Reporting Entity Status
. sort descending
NZBN
. sort descending
Actions
EROAD LIMITED Registered 9429037254377
F&C INVESTMENT TRUST PLC Registered 9429038734472
FIDELITY LIFE ASSURANCE COMPANY LIMITED Registered 9429040548623
FIRST MORTGAGE MANAGERS LIMITED Registered 9429038360961
FISHER & PAYKEL HEALTHCARE CORPORATION LIMITED Registered 9429040719887
FISHER FUNDS MANAGEMENT LIMITED Registered 9429037864354
FLETCHER BUILDING INDUSTRIES LIMITED Registered 9429036277827
FLETCHER BUILDING LIMITED Registered 9429037065836
FMG INSURANCE LIMITED Registered 9429034181225
FOLEY WINES LIMITED Registered 9429000001311
Table on Page 6:
CRE Name
. sort ascending
Reporting Entity Status
. sort descending
NZBN
. sort descending
Actions
FONTERRA CO-OPERATIVE GROUP LIMITED Registered 9429036748471
FREIGHTWAYS GROUP LIMITED Registered 9429036246380
FUNDROCK NZ LIMITED Registered 9429031398602
GENERATE INVESTMENT MANAGEMENT LIMITED Registered 9429030374034
GENESIS ENERGY LIMITED Registered 9429037706609
GENTRACK GROUP LIMITED Registered 9429030723047
GMT BOND ISSUER LIMITED Registered 9429031789004
GOODMAN (NZ) LIMITED Registered 9429035627104
GREEN CROSS HEALTH LIMITED Registered 9429037684754
HARBOUR ASSET MANAGEMENT LIMITED Registered 9429034228791
Table on Page 7:
CRE Name
. sort ascending
Reporting Entity Status
. sort descending
NZBN
. sort descending
Actions
HEARTLAND BANK LIMITED Registered 9429031360449
HEARTLAND GROUP HOLDINGS LIMITED Registered 9429046912374
HOUSING NEW ZEALAND LIMITED Registered 9429038996009
IAG NEW ZEALAND LIMITED Registered 9429039302748
IKEGPS GROUP LIMITED Registered 9429036029341
INDUSTRIAL AND COMMERCIAL BANK OF CHINA (NEW ZEALAND) LIMITED Registered 9429030309739
INDUSTRIAL AND COMMERCIAL BANK OF CHINA LIMITED Registered 9429048239035
INFRATIL LIMITED Registered 9429038818684
INSURANCE AUSTRALIA GROUP LIMITED Registered
INVESTORE PROPERTY LIMITED Registered 9429042006237
Table on Page 8:
CRE Name
. sort ascending
Reporting Entity Status
. sort descending
NZBN
. sort descending
Actions
JPMORGAN CHASE BANK, N.A. Registered 9429033103686
KINGFISH LIMITED Registered 9429035571216
KIWI PROPERTY GROUP LIMITED Registered 9429041457610
KIWI WEALTH INVESTMENTS LIMITED PARTNERSHIP Registered 9429043093236
KIWI WEALTH LIMITED Registered 9429034404119
KIWIBANK LIMITED Registered 9429036917211
KMD BRANDS LIMITED Registered 9429000024440
LIVESTOCK IMPROVEMENT CORPORATION LIMITED Registered 9429039566119
MAINFREIGHT LIMITED Registered 9429040418087
MANAWA ENERGY LIMITED Registered 9429038917912
Table on Page 9:
CRE Name
. sort ascending
Reporting Entity Status
. sort descending
NZBN
. sort descending
Actions
MARLIN GLOBAL LIMITED Registered 9429033149561
MARSDEN MARITIME HOLDINGS LIMITED Registered 9429039463005
MEDICAL FUNDS MANAGEMENT LIMITED Registered 9429039171085
MERCER (N.Z.) LIMITED Registered 9429040873121
MERCURY NZ LIMITED Registered 9429037705305
MERIDIAN ENERGY LIMITED Registered 9429037696863
METLIFECARE LIMITED Registered 9429039960740
MICHAEL HILL INTERNATIONAL LIMITED Registered
MILFORD FUNDS LIMITED Registered 9429033222271
MILLENNIUM & COPTHORNE HOTELS NEW ZEALAND LIMITED Registered 9429039146045
Table on Page 10:
CRE Name
. sort ascending
Reporting Entity Status
. sort descending
NZBN
. sort descending
Actions
MOVE LOGISTICS GROUP LIMITED Registered 9429037363611
MUFG BANK, LTD. Registered 9429035544883
NELSON BUILDING SOCIETY Registered 9429043042661
NEW ZEALAND FUNDS MANAGEMENT LIMITED Registered 9429039444158
NEW ZEALAND KING SALMON INVESTMENTS LIMITED Registered 9429032611540
NEW ZEALAND LOCAL GOVERNMENT FUNDING AGENCY LIMITED Registered 9429030861961
NEW ZEALAND OIL & GAS LIMITED Registered 9429040785714
NEW ZEALAND RURAL LAND COMPANY LIMITED Registered 9429048619509
NIB NZ LIMITED Registered 9429038788932
NIKKO ASSET MANAGEMENT NEW ZEALAND LIMITED Registered 9429038788291
Table on Page 11:
CRE Name
. sort ascending
Reporting Entity Status
. sort descending
NZBN
. sort descending
Actions
NORTHWEST HEALTHCARE PROPERTIES MANAGEMENT LIMITED Registered 9429038991493
NZME LIMITED Registered 9429036668007
NZX LIMITED Registered 9429036186358
OCEANIA HEALTHCARE LIMITED Registered 9429034676066
PACIFIC EDGE LIMITED Registered 9429036991945
PARTNERS LIFE LIMITED Registered 9429031409889
PGG WRIGHTSON LIMITED Registered 9429040323497
PIE FUNDS MANAGEMENT LIMITED Registered 9429033253800
PORT OF TAURANGA LIMITED Registered 9429039540300
PRECINCT PROPERTIES NEW ZEALAND LIMITED Registered 9429031565783
Table on Page 12:
CRE Name
. sort ascending
Reporting Entity Status
. sort descending
NZBN
. sort descending
Actions
PROPERTY FOR INDUSTRY LIMITED Registered 9429038826672
QBE INSURANCE (AUSTRALIA) LIMITED Registered 9429042054160
QUAYSIDE HOLDINGS LIMITED Registered 9429039147226
RABOBANK NEW ZEALAND LIMITED Registered 9429040969855
RADIUS RESIDENTIAL CARE LIMITED Registered 9429035991007
RAKON LIMITED Registered 9429039193186
RESOLUTION LIFE AUSTRALASIA LIMITED Registered 9429039817211
RESTAURANT BRANDS NEW ZEALAND LIMITED Registered 9429038138775
RYMAN HEALTHCARE LIMITED Registered 9429039629517
SANFORD LIMITED Registered 9429000010856
Table on Page 13:
CRE Name
. sort ascending
Reporting Entity Status
. sort descending
NZBN
. sort descending
Actions
SCALES CORPORATION LIMITED Registered 9429039355249
SEEKA LIMITED Registered 9429039617347
SERKO LIMITED Registered 9429033492179
SIMPLICITY NZ LIMITED Registered 9429041767092
SKELLERUP HOLDINGS LIMITED Registered 9429039662606
SKY NETWORK TELEVISION LIMITED Registered 9429035067818
SKYCITY ENTERTAINMENT GROUP LIMITED Registered 9429038769528
SMARTPAY HOLDINGS LIMITED Registered 9429039735690
SMARTSHARES LIMITED Registered 9429038512483
SOUTH PORT NEW ZEALAND LIMITED Registered 9429039452528

Table on Page 14:
CRE Name
. sort ascending
Reporting Entity Status
. sort descending
NZBN
. sort descending
Actions
SOUTHERN CROSS MEDICAL CARE SOCIETY Registered 9429043036400
SOUTHLAND BUILDING SOCIETY Registered 9429043042654
SPARK FINANCE LIMITED Registered 9429039076847
SPARK NEW ZEALAND LIMITED Registered 9429039661098
STEEL & TUBE HOLDINGS LIMITED Registered 9429040949390
STRIDE INVESTMENT MANAGEMENT LIMITED Registered 9429042189435
STRIDE PROPERTY LIMITED Registered 9429035963950
SUMMERSET GROUP HOLDINGS LIMITED Registered 9429035141679
SWISS RE LIFE & HEALTH AUSTRALIA LIMITED Registered 9429040975696
T&G GLOBAL LIMITED Registered 9429040750705
Table on Page 15:
CRE Name
. sort ascending
Reporting Entity Status
. sort descending
NZBN
. sort descending
Actions
TEMPLETON EMERGING MARKETS INVESTMENT TRUST PUBLIC LIMITED COMPANY Registered 9429038745980
THE A2 MILK COMPANY LIMITED Registered 9429037368845
THE CITY OF LONDON INVESTMENT TRUST PLC Registered 9429036466658
THE COLONIAL MOTOR COMPANY LIMITED Registered 9429040973531
THE CO-OPERATIVE BANK LIMITED Registered 9429037734121
THE HOLLARD INSURANCE COMPANY PTY LTD Registered 9429042129851
THE HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED Registered 9429039532039
TOURISM HOLDINGS LIMITED Registered 9429039926081
TRANSPOWER NEW ZEALAND LIMITED Registered 9429039514226
TSB BANK LIMITED Registered 9429039413291
Table on Page 16:
CRE Name
. sort ascending
Reporting Entity Status
. sort descending
NZBN
. sort descending
Actions
TURNERS AUTOMOTIVE GROUP LIMITED Registered 9429039926999
VECTOR LIMITED Registered 9429039215109
VENTIA SERVICES GROUP LIMITED Registered 9429050093786
VERO INSURANCE NEW ZEALAND LIMITED Registered 9429040973210
VISTA GROUP INTERNATIONAL LIMITED Registered 9429035866336
VULCAN STEEL LIMITED Registered 9429038466052
WELLINGTON INTERNATIONAL AIRPORT LIMITED Registered 9429039443755
WINTON LAND LIMITED Registered 9429046190154
WORKS FINANCE (NZ) LIMITED Registered 9429033605623
Z ENERGY LIMITED Registered 9429040935874

In [8]:
table_final.columns = ['CRE Name','Reporting Entity Status','NZBN','Actions','Link']
table_final.drop(0, inplace=True)
table_final.head(5)

,CRE Name,Reporting Entity Status,NZBN,Actions,Link
1,AA INSURANCE LIMITED,Registered,9429040865966,View details,[/dashboard/reportingentity/?id=8b6b5ca5-8394-...
2,AFT PHARMACEUTICALS LIMITED,Registered,9429038010415,View details,[/dashboard/reportingentity/?id=a96b5ca5-8394-...
3,AIA NEW ZEALAND LIMITED,Registered,9429039580948,View details,[/dashboard/reportingentity/?id=8d6b5ca5-8394-...
4,AIR NEW ZEALAND LIMITED,Registered,9429040402543,View details,[/dashboard/reportingentity/?id=ab6b5ca5-8394-...
5,AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED,Registered,9429038259210,View details,[/dashboard/reportingentity/?id=696c5ca5-8394-...

In [16]:
today = date.today().strftime("%d/%m/%Y")
table_final.to_csv(f'{folder}/table_final.csv')

In [17]:
today

'07/05/2024'

In [20]:
table_final = pd.read_csv(f'{folder}/table_final.csv')
## This URL represents the link to CRD hub.  
masterlink= 'https://crd-app.companiesoffice.govt.nz'

links_final = pd.DataFrame()
for index, row in table_final.iterrows():
    firm_name = row['CRE Name']
    links = [masterlink + link for link in ast.literal_eval(row.Link)]
    df = pd.DataFrame({'CRE Name': [row['CRE Name']] * len(links), 'Link': links})
    links_final = pd.concat([links_final, df],ignore_index = True)
links_final.head(5)
links_final.to_csv(f'{folder}/links_final.csv')

This step is to extract the link and download pdf files from all  entities again

In [21]:
links_final = pd.read_csv(f'{folder}/links_final.csv')
## This URL represents the link to CRD hub.  
masterlink= 'https://crd-app.companiesoffice.govt.nz'

# extract  data 
table_details_final = pd.DataFrame()

for index, row in links_final.iterrows():
    firm_name = row['CRE Name']
    print(firm_name)
    link = row.Link

    # open the browser to activate the process using the URL defined 
    driver.get(link)
    
    time.sleep(3)
       
    # Wait for the table to become visible
    table = WebDriverWait(driver, 30).until(
        EC.visibility_of_element_located((By.CSS_SELECTOR, "table"))
    )
    
    text = table.text
    print(text)
    # Create a dictionary with the row data
    row_data = pd.DataFrame([{
        'Link': link,
        'Company Name': firm_name,
        'Text': text
    }])
    # After obtaining the table, you can perform any further actions required
    table_details_final = pd.concat([table_details_final, row_data], ignore_index=True)

table_details_final.to_csv(f'{folder}/ltable_details_final.csv')

AA INSURANCE LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
AFT PHARMACEUTICALS LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
AIA NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
AIR NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
AMP INVESTMENT TRUST (SCH10721) Registered AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
AMP KIWISAVER SCHEME (SCH10367) Registered AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
AMP MANAGED FUNDS (SCH13265) Registered AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
AMP PASSIVE PERSONAL RETIREMENT PLAN - INTERNATIONAL PASSIVE SHARES INVESTMENT FUND (SCH10821) Registered AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
AMP PASSIVE PERSONAL RETIREMENT PLAN - NEW ZEALAND PASSIVE SHARES INVESTMENT FUND (SCH10822) Registered AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
AMP PERSONAL RETIREMENT PLAN (SCH10820) Registered AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
NEW ZEALAND RETIREMENT TRUST (SCH10911) Registered AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
ANZ INVESTMENT SERVICES (NEW ZEALAND) LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
BONUS BONDS SCHEME (SCH11094) Registered ANZ INVESTMENT SERVICES (NEW ZEALAND) LIMITED
ANZ NEW ZEALAND INVESTMENTS LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
ANZ DEFAULT KIWISAVER SCHEME (SCH11063) Registered ANZ NEW ZEALAND INVESTMENTS LIMITED
ANZ INVESTMENTS MULTI-ASSET-CLASS SCHEME (MARKETED AS THE ANZ INVESTMENT FUNDS AND ONEANSWER MULTI-ASSET-CLASS FUNDS) (SCH11064) Registered ANZ NEW ZEALAND INVESTMENTS LIMITED
ANZ INVESTMENTS SINGLE-ASSET-CLASS SCHEME (MARKETED AS THE ONEANSWER SINGLE-ASSET-CLASS FUNDS) (SCH11065) Registered ANZ NEW ZEALAND INVESTMENTS LIMITED
ANZ KIWISAVER SCHEME (SCH11062) Registered ANZ NEW ZEALAND INVESTMENTS LIMITED
ONEANSWER KIWISAVER SCHEME (SCH11061) Registered ANZ NEW ZEALAND INVESTMENTS LIMITED
ARBORGEN HOLDINGS LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
ARGOSY PROPERTY LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
ARVIDA GROUP LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
ASB BANK LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
ASB GROUP INVESTMENTS LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
ASB INVESTMENT FUNDS (SCH10685) Registered ASB GROUP INVESTMENTS LIMITED
ASB KIWISAVER SCHEME (SCH10678) Registered ASB GROUP INVESTMENTS LIMITED
ASSET PLUS LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
ASTERON LIFE LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
AUCKLAND COUNCIL
Reporting Period
. sort descending
Actions
There are no records to display.
AUCKLAND INTERNATIONAL AIRPORT LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
AUSTRALIAN FOUNDATION INVESTMENT COMPANY LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
BANK OF CHINA (NEW ZEALAND) LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
BANK OF CHINA LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Due by 30-04-2024
BARRAMUNDI LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
BNZ INVESTMENT SERVICES LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
BNZ KIWISAVER SCHEME (SCH10701) Registered BNZ INVESTMENT SERVICES LIMITED
PRIVATE WEALTH SERIES (SCH11384) Registered BNZ INVESTMENT SERVICES LIMITED
YOUWEALTH (SCH12341) Registered BNZ INVESTMENT SERVICES LIMITED
BOOSTER INVESTMENT MANAGEMENT LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
BOOSTER INNOVATION SCHEME (SCH13202) Registered BOOSTER INVESTMENT MANAGEMENT LIMITED
BOOSTER INVESTMENT SCHEME (SCH10844) Registered BOOSTER INVESTMENT MANAGEMENT LIMITED
BOOSTER INVESTMENT SCHEME 2 (SCH12548) Registered BOOSTER INVESTMENT MANAGEMENT LIMITED
BOOSTER KIWISAVER SCHEME (SCH10841) Registered BOOSTER INVESTMENT MANAGEMENT LIMITED
BOOSTER SAVVY SCHEME (SCH13546) Registered BOOSTER INVESTMENT MANAGEMENT LIMITED
BOOSTER SUPERSCHEME (SCH11323) Registered BOOSTER INVESTMENT MANAGEMENT LIMITED
BRISCOE GROUP LIMITED
Reporting Period
. sort descending
Actions
31-01-2024 - Click to view Climate Statement/s
BT FUNDS MANAGEMENT (NZ) LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
WESTPAC ACTIVE SERIES (SCH10564) Registered BT FUNDS MANAGEMENT (NZ) LIMITED
WESTPAC KIWISAVER SCHEME (SCH10585) Registered BT FUNDS MANAGEMENT (NZ) LIMITED
WESTPAC PREMIUM INVESTMENT FUNDS (SCH10817) Registered BT FUNDS MANAGEMENT (NZ) LIMITED
WESTPAC RETIREMENT PLAN (SCH11614) Registered BT FUNDS MANAGEMENT (NZ) LIMITED
CDL INVESTMENTS NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
33 BROADWAY TRUST (SCH11912) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
AIRPARK NOMINEES JOINT VENTURE (SCH11740) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
AUGUSTA KEDRON PARTNERSHIP (SCH12564) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
AUGUSTA ST GEORGES BAY ROAD PROPERTY TRUST (SCH12448) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
BIRCH NOMINEES JOINT VENTURE (SCH11560) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
BRADMAN STREET PROPORTIONATE OWNERSHIP SCHEME (SCH11503) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
BUILDING A GRAHAM STREET LIMITED PARTNERSHIP (SCH10571) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
BUILDING B GRAHAM STREET LIMITED PARTNERSHIP (SCH10922) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
CENTURIA NZ PROPERTY FUND (SCH12900) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
FERNHILL NOMINEES JOINT VENTURE (SCH11564) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
FORMATION ST PROPORTIONATE OWNERSHIP SCHEME (SCH11478) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
HIBISCUS NOMINEES JOINT VENTURES (SCH11466) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
LAMBIE DR PROPERTY SCHEME (SCH11586) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
LINK DR PROPERTY SCHEME (SCH11587) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
MANADON STREET PROPERTY SCHEME (SCH11532) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
PEACHGROVE ROAD LIMITED PARTNERSHIP (SCH11471) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
QUINNS HILL ROAD PARTNERSHIP (SCH10523) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
SHANDS ROAD LIMITED PARTNERSHIP (SCH11468) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
SHERBROOKE RD PARTNERSHIP (SCH11507) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
SIR WILLIAM PICKERING DRIVE LIMITED PARTNERSHIP (SCH12323) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
TAKANINI NOMINEES JOINT VENTURE (SCH11465) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
VICKERS ROAD PROPERTY SCHEME (SCH11556) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
WESTPOINT PROPERTY SCHEME (SCH11602) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
WILLIAMS STREET NOMINEES JOINT VENTURE (SCH11570) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
CHANNEL INFRASTRUCTURE NZ LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
CHINA CONSTRUCTION BANK (NEW ZEALAND) LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
CHINA CONSTRUCTION BANK CORPORATION
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
CHORUS LIMITED

Reporting Period
. sort descending
Actions
There are no records to display.
CHRISTCHURCH CITY HOLDINGS LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
CHRISTCHURCH INTERNATIONAL AIRPORT LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
CHUBB LIFE INSURANCE NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
CITIBANK, N.A.
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
COMMONWEALTH BANK OF AUSTRALIA
Reporting Period
. sort descending
Actions
There are no records to display.
COMVITA LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
CONTACT ENERGY LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
COOPERATIEVE RABOBANK U.A.
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
DELEGAT GROUP LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
EBOS GROUP LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
EROAD LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
F&C INVESTMENT TRUST PLC
Reporting Period
. sort descending
Actions
31-12-2023 - Due by 30-04-2024
FIDELITY LIFE ASSURANCE COMPANY LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
FIRST MORTGAGE MANAGERS LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
FIRST MORTGAGE PIE TRUST (SCH10249) Registered FIRST MORTGAGE MANAGERS LIMITED
FIRST MORTGAGE TRUST GROUP INVESTMENT FUND (SCH10239) Registered FIRST MORTGAGE MANAGERS LIMITED
FISHER & PAYKEL HEALTHCARE CORPORATION LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FISHER FUNDS MANAGEMENT LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
FISHER FUNDS INVESTMENT SERIES (SCH10642) Registered FISHER FUNDS MANAGEMENT LIMITED
FISHER FUNDS KIWISAVER SCHEME (SCH10636) Registered FISHER FUNDS MANAGEMENT LIMITED
FISHER FUNDS LIFESAVER PLAN (SCH10637) Registered FISHER FUNDS MANAGEMENT LIMITED
FISHER FUNDS MANAGED FUNDS (SCH10640) Registered FISHER FUNDS MANAGEMENT LIMITED
FISHER FUNDS PREMIUM SERVICE (SCH10641) Registered FISHER FUNDS MANAGEMENT LIMITED
FISHER FUNDS TWO KIWISAVER SCHEME (SCH10597) Registered FISHER FUNDS MANAGEMENT LIMITED
FUTUREPLAN (SCH11318) Registered FISHER FUNDS MANAGEMENT LIMITED
FLETCHER BUILDING INDUSTRIES LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
FLETCHER BUILDING LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
FMG INSURANCE LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FOLEY WINES LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
FONTERRA CO-OPERATIVE GROUP LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
FREIGHTWAYS GROUP LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
FUNDROCK NZ LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
ACI FUNDS (SCH13499) Registered FUNDROCK NZ LIMITED
ANTIPODES INVESTMENT FUNDS (SCH12434) Registered FUNDROCK NZ LIMITED
APN INVESTMENT FUNDS SCHEME (SCH11734) Registered FUNDROCK NZ LIMITED
AURORA KIWISAVER SCHEME (SCH13055) Registered FUNDROCK NZ LIMITED
BENTHAM INVESTMENT FUNDS (SCH13506) Registered FUNDROCK NZ LIMITED
COLCHESTER INVESTMENT FUNDS (SCH13056) Registered FUNDROCK NZ LIMITED
COOLABAH INVESTMENT FUNDS (SCH13148) Registered FUNDROCK NZ LIMITED
DIMENSIONAL INVESTMENT FUNDS (SCH13317) Registered FUNDROCK NZ LIMITED
FIRST SENTIER INVESTORS (NZ) SCHEME (SCH13089) Registered FUNDROCK NZ LIMITED
FOUNDATION SERIES FUNDS (SCH13175) Registered FUNDROCK NZ LIMITED
FRANKLIN TEMPLETON INVESTMENT FUNDS (SCH12302) Registered FUNDROCK NZ LIMITED
HOBSON WEALTH INVESTMENT FUNDS (SCH12667) Registered FUNDROCK NZ LIMITED
HYPERION INVESTMENT FUNDS (SCH13281) Registered FUNDROCK NZ LIMITED
INVESTNOW KIWISAVER SCHEME (SCH12874) Registered FUNDROCK NZ LIMITED
LIGHTHOUSE INVESTMENT FUNDS (SCH13048) Registered FUNDROCK NZ LIMITED
RUSSELL INVESTMENT FUNDS (SCH10586) Registered FUNDROCK NZ LIMITED
SCHRODER INVESTMENT FUNDS (SCH13639) Registered FUNDROCK NZ LIMITED
SQUIRREL INVESTMENT FUNDS (SCH13142) Registered FUNDROCK NZ LIMITED
STEWART INVESTORS (NZ) MANAGED INVESTMENT SCHEME (SCH13295) Registered FUNDROCK NZ LIMITED
TE AHUMAIRANGI INVESTMENT FUNDS (SCH13146) Registered FUNDROCK NZ LIMITED
VAULT DIGITAL FUNDS (SCH13147) Registered FUNDROCK NZ LIMITED
VISION INVEST NZ FUNDS (SCH12865) Registered FUNDROCK NZ LIMITED
GENERATE INVESTMENT MANAGEMENT LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
GENERATE KIWISAVER SCHEME (SCH10791) Registered GENERATE INVESTMENT MANAGEMENT LIMITED
GENERATE UNIT TRUST SCHEME (SCH12736) Registered GENERATE INVESTMENT MANAGEMENT LIMITED
GENESIS ENERGY LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
GENTRACK GROUP LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
GMT BOND ISSUER LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
GOODMAN (NZ) LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
GOODMAN PROPERTY TRUST (SCH11225) Registered GOODMAN (NZ) LIMITED
GREEN CROSS HEALTH LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
HARBOUR ASSET MANAGEMENT LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
HARBOUR INVESTMENT FUNDS (SCH10815) Registered HARBOUR ASSET MANAGEMENT LIMITED
HUNTER INVESTMENT FUNDS (SCH11176) Registered HARBOUR ASSET MANAGEMENT LIMITED
HEARTLAND BANK LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
HEARTLAND GROUP HOLDINGS LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
HOUSING NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
IAG NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
IKEGPS GROUP LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
INDUSTRIAL AND COMMERCIAL BANK OF CHINA (NEW ZEALAND) LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
INDUSTRIAL AND COMMERCIAL BANK OF CHINA LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
INFRATIL LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
INSURANCE AUSTRALIA GROUP LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
INVESTORE PROPERTY LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
JPMORGAN CHASE BANK, N.A.
Reporting Period
. sort descending
Actions
31-12-2023 - Due by 30-04-2024
KINGFISH LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
KIWI PROPERTY GROUP LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
KIWI WEALTH INVESTMENTS LIMITED PARTNERSHIP
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
KIWI WEALTH SUPER SCHEME (SCH10814) Registered KIWI WEALTH INVESTMENTS LIMITED PARTNERSHIP
KIWI WEALTH LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
KIWI WEALTH KIWISAVER SCHEME (SCH10713) Registered KIWI WEALTH LIMITED
KIWI WEALTH MANAGED FUNDS (SCH12389) Registered KIWI WEALTH LIMITED
KIWIBANK LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
KMD BRANDS LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
LIVESTOCK IMPROVEMENT CORPORATION LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
MAINFREIGHT LIMITED

Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
MANAWA ENERGY LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
MARLIN GLOBAL LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
MARSDEN MARITIME HOLDINGS LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
MEDICAL FUNDS MANAGEMENT LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
MAS INVESTMENT FUNDS  (SCH13659) Registered MEDICAL FUNDS MANAGEMENT LIMITED
MAS KIWISAVER SCHEME (SCH10705) Registered MEDICAL FUNDS MANAGEMENT LIMITED
MAS RETIREMENT SAVINGS SCHEME (SCH10706) Registered MEDICAL FUNDS MANAGEMENT LIMITED
MERCER (N.Z.) LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
DEFENCE FORCE SUPERANNUATION SCHEME (SCH11069) Registered MERCER (N.Z.) LIMITED
MERCER FLEXISAVER (SCH10280) Registered MERCER (N.Z.) LIMITED
MERCER INVESTMENT FUNDS (SCH10307) Registered MERCER (N.Z.) LIMITED
MERCER KIWISAVER SCHEME (SCH10245) Registered MERCER (N.Z.) LIMITED
MERCER SUPER TRUST (SCH10697) Registered MERCER (N.Z.) LIMITED
NEW ZEALAND DEFENCE FORCE KIWISAVER SCHEME (SCH10279) Registered MERCER (N.Z.) LIMITED
MERCURY NZ LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
MERIDIAN ENERGY LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
METLIFECARE LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
MICHAEL HILL INTERNATIONAL LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
MILFORD FUNDS LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
MILFORD INVESTMENT FUNDS (SCH10700) Registered MILFORD FUNDS LIMITED
MILFORD KIWISAVER PLAN (SCH10498) Registered MILFORD FUNDS LIMITED
MILLENNIUM & COPTHORNE HOTELS NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
MOVE LOGISTICS GROUP LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
MUFG BANK, LTD.
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
NELSON BUILDING SOCIETY
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
NEW ZEALAND FUNDS MANAGEMENT LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
NZ FUNDS KIWISAVER SCHEME (SCH10783) Registered NEW ZEALAND FUNDS MANAGEMENT LIMITED
NZ FUNDS MANAGED PORTFOLIO SERVICE PART ONE (SCH10786) Registered NEW ZEALAND FUNDS MANAGEMENT LIMITED
NZ FUNDS MANAGED PORTFOLIO SERVICE PART TWO (SCH10803) Registered NEW ZEALAND FUNDS MANAGEMENT LIMITED
NZ FUNDS MANAGED SUPERANNUATION SERVICE (SCH11205) Registered NEW ZEALAND FUNDS MANAGEMENT LIMITED
NEW ZEALAND KING SALMON INVESTMENTS LIMITED
Reporting Period
. sort descending
Actions
31-01-2024 - Due by 31-05-2024
NEW ZEALAND LOCAL GOVERNMENT FUNDING AGENCY LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
NEW ZEALAND OIL & GAS LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
NEW ZEALAND RURAL LAND COMPANY LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
NIB NZ LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
NIKKO ASSET MANAGEMENT NEW ZEALAND LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
NIKKO AM KIWISAVER SCHEME (SCH12354) Registered NIKKO ASSET MANAGEMENT NEW ZEALAND LIMITED
NIKKO AM NZ INVESTMENT SCHEME (SCH10488) Registered NIKKO ASSET MANAGEMENT NEW ZEALAND LIMITED
NORTHWEST HEALTHCARE PROPERTIES MANAGEMENT LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
VITAL HEALTHCARE PROPERTY TRUST (SCH11214) Registered NORTHWEST HEALTHCARE PROPERTIES MANAGEMENT LIMITED
NZME LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
NZX LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
OCEANIA HEALTHCARE LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
PACIFIC EDGE LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
PARTNERS LIFE LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
PGG WRIGHTSON LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
PIE FUNDS MANAGEMENT LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
JUNO KIWISAVER SCHEME (SCH12451) Registered PIE FUNDS MANAGEMENT LIMITED
PIE FUNDS MANAGEMENT SCHEME (SCH10581) Registered PIE FUNDS MANAGEMENT LIMITED
PORT OF TAURANGA LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
PRECINCT PROPERTIES NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
PROPERTY FOR INDUSTRY LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
QBE INSURANCE (AUSTRALIA) LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
QUAYSIDE HOLDINGS LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
RABOBANK NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
RADIUS RESIDENTIAL CARE LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
RAKON LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
RESOLUTION LIFE AUSTRALASIA LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
RESTAURANT BRANDS NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
RYMAN HEALTHCARE LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
SANFORD LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
SCALES CORPORATION LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
SEEKA LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
SERKO LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
SIMPLICITY NZ LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
SIMPLICITY INVESTMENT FUNDS (SCH11873) Registered SIMPLICITY NZ LIMITED
SIMPLICITY KIWISAVER SCHEME (SCH10736) Registered SIMPLICITY NZ LIMITED
SKELLERUP HOLDINGS LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
SKY NETWORK TELEVISION LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
SKYCITY ENTERTAINMENT GROUP LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
SMARTPAY HOLDINGS LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
SMARTSHARES LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
NZ CORE EQUITY TRUST (SCH10764) Registered SMARTSHARES LIMITED
QUAYSTREET FUNDS (SCH10414) Registered SMARTSHARES LIMITED
QUAYSTREET KIWISAVER SCHEME (SCH10663) Registered SMARTSHARES LIMITED
SELECT KIWISAVER SCHEME (SCH13004) Registered SMARTSHARES LIMITED
SMARTSHARES EXCHANGE TRADED FUNDS (SCH10752) Registered SMARTSHARES LIMITED
SUPERLIFE INVEST (SCH10765) Registered SMARTSHARES LIMITED
SUPERLIFE KIWISAVER SCHEME (SCH10768) Registered SMARTSHARES LIMITED
SUPERLIFE SUPERANNUATION MASTER TRUST (SCH10688) Registered SMARTSHARES LIMITED
SUPERLIFE UK PENSION TRANSFER SCHEME (SCH10767) Registered SMARTSHARES LIMITED
SUPERLIFE WORKPLACE SAVINGS SCHEME (SCH10769) Registered SMARTSHARES LIMITED
SOUTH PORT NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
SOUTHERN CROSS MEDICAL CARE SOCIETY

Reporting Period
. sort descending
Actions
There are no records to display.
SOUTHLAND BUILDING SOCIETY
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
SPARK FINANCE LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
SPARK NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
STEEL & TUBE HOLDINGS LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
STRIDE INVESTMENT MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
STRIDE PROPERTY LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
SUMMERSET GROUP HOLDINGS LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
SWISS RE LIFE & HEALTH AUSTRALIA LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
T&G GLOBAL LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
TEMPLETON EMERGING MARKETS INVESTMENT TRUST PUBLIC LIMITED COMPANY
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
THE A2 MILK COMPANY LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
THE CITY OF LONDON INVESTMENT TRUST PLC
Reporting Period
. sort descending
Actions
There are no records to display.
THE COLONIAL MOTOR COMPANY LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
THE CO-OPERATIVE BANK LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
THE HOLLARD INSURANCE COMPANY PTY LTD
Reporting Period
. sort descending
Actions
There are no records to display.
THE HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
TOURISM HOLDINGS LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
TRANSPOWER NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
TSB BANK LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
TURNERS AUTOMOTIVE GROUP LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
VECTOR LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
VENTIA SERVICES GROUP LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
VERO INSURANCE NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
VISTA GROUP INTERNATIONAL LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s
VULCAN STEEL LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
WELLINGTON INTERNATIONAL AIRPORT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
WINTON LAND LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
WORKS FINANCE (NZ) LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
Z ENERGY LIMITED
Reporting Period
. sort descending
Actions
31-12-2023 - Click to view Climate Statement/s

In [25]:
#Work a bit more on table detail
table_details_final = pd.read_csv(f'{folder}/table_details_final.csv')
# Clean up the 'Text' column
table_details_final['text_new'] = table_details_final['Text'].str.replace('\n', '|') \
                                                              .str.replace('Reporting Period', '') \
                                                              .str.replace('. sort descending', '') \
                                                              .str.replace('. sort ascending', '') \
                                                              .str.replace('Scheme', '')\
                                                              .str.replace('Scheme Status', '')\
                                                              .str.replace('Reporting Entity', '')\
                                                              .str.replace('Status', '')\
                                                              .str.replace('Registered', '_')\
                                                   .str.replace('Actions', '')\


# Display the DataFrame
print(table_details_final.head(5))

table_details_final.to_csv(f'{folder}/table_details_final.new.csv')

   Unnamed: 0                                               Link  \
0           0  https://crd-app.companiesoffice.govt.nz/dashbo...
1           1  https://crd-app.companiesoffice.govt.nz/dashbo...
2           2  https://crd-app.companiesoffice.govt.nz/dashbo...
3           3  https://crd-app.companiesoffice.govt.nz/dashbo...
4           4  https://crd-app.companiesoffice.govt.nz/dashbo...

                                Company Name  \
0                       AA INSURANCE LIMITED
1                AFT PHARMACEUTICALS LIMITED
2                    AIA NEW ZEALAND LIMITED
3                    AIR NEW ZEALAND LIMITED
4  AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED

                                                Text  \
0  Reporting Period\n. sort descending\nActions\n...
1  Reporting Period\n. sort descending\nActions\n...
2  Reporting Period\n. sort descending\nActions\n...
3  Reporting Period\n. sort descending\nActions\n...
4  Scheme\n. sort ascending\nScheme Status\n. sor...

                                            text_new
0                |||There are no records to display.
1                  |||31-03-2024 - Due by 31-07-2024
2  |||31-12-2023 - Click to view Climate Statement/s
3                |||There are no records to display.
4  || |||||AMP INVESTMENT TRUST (SCH10721) _ AMP ...

In [26]:
table_details_final = pd.read_csv(f'{folder}/table_details_final.new.csv') 

#Get the scheme list:
# Search for rows containing 'scheme' in the 'Text' column
scheme_rows = table_details_final[table_details_final['Text'].str.contains('Scheme', case=False)]

print(scheme_rows.shape)
# Display the rows containing 'scheme'
scheme_rows.head(5)


## This URL represents the link to CRD hub.  
masterlink= 'https://crd-app.companiesoffice.govt.nz'

# extract  data 
table_details_final_scheme = pd.DataFrame()

for index, row in scheme_rows.iterrows():
    firm_name = row['Company Name']
    print(firm_name)
    link = row.Link

    # open the browser to activate the process using the URL defined 
    driver.get(link)
    
    time.sleep(3)
       
    # Wait for the table to become visible
    table = WebDriverWait(driver, 30).until(
        EC.visibility_of_element_located((By.CSS_SELECTOR, "table"))
    )
    
    text = table.text
    print(text)
    
    # Get the table HTML
    table_html = table.get_attribute("outerHTML")
    
    #Extract table data
    # Parse the HTML table content with BeautifulSoup
    soup = BeautifulSoup(table_html, 'html.parser')

    # Extract table rows
    rows = soup.find_all('tr')

    # Initialize lists to store table data and associated links
    table_data = []

    # Loop through table rows
    for row in rows[2:]:
        # Extract table cells (columns)
        cells = row.find_all(['td'])
        row_data = []
        for cell in cells:
            # Extract text from cell
            cell_text = cell.get_text(strip=True)
            row_data.append(cell_text)
        links = []
        # Check if cell contains a link
        link = cell.find('a')
        if link:
            # Extract link URL
            link_url = link.get('href')
            links.append(link_url)

        # Remove duplicates using set
        unique_href_values = set(links)

        # Filter out only the elements starting with '/dashboard/reportingentity/?id='
        filtered_href_values = [href for href in unique_href_values if href.startswith('/dashboard/reportingentity/')]

        row_data.append(filtered_href_values)
        # Append row data to table data
        table_data.append(row_data)

    # Convert table data to DataFrame
    table_df = pd.DataFrame(table_data)
    
    # After obtaining the table, you can perform any further actions required
    table_details_final_scheme = pd.concat([table_details_final_scheme, table_df], ignore_index=True)
table_details_final_scheme.columns = ['Scheme','Scheme Status','Company Name','Detail','Link']
table_details_final_scheme.dropna(subset=['Detail'],inplace=True)
table_details_final_scheme.to_csv(f'{folder}/table_details_final_scheme.csv')

(25, 6)
AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
AMP INVESTMENT TRUST (SCH10721) Registered AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
AMP KIWISAVER SCHEME (SCH10367) Registered AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
AMP MANAGED FUNDS (SCH13265) Registered AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
AMP PASSIVE PERSONAL RETIREMENT PLAN - INTERNATIONAL PASSIVE SHARES INVESTMENT FUND (SCH10821) Registered AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
AMP PASSIVE PERSONAL RETIREMENT PLAN - NEW ZEALAND PASSIVE SHARES INVESTMENT FUND (SCH10822) Registered AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
AMP PERSONAL RETIREMENT PLAN (SCH10820) Registered AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
NEW ZEALAND RETIREMENT TRUST (SCH10911) Registered AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
ANZ INVESTMENT SERVICES (NEW ZEALAND) LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
BONUS BONDS SCHEME (SCH11094) Registered ANZ INVESTMENT SERVICES (NEW ZEALAND) LIMITED
ANZ NEW ZEALAND INVESTMENTS LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
ANZ DEFAULT KIWISAVER SCHEME (SCH11063) Registered ANZ NEW ZEALAND INVESTMENTS LIMITED
ANZ INVESTMENTS MULTI-ASSET-CLASS SCHEME (MARKETED AS THE ANZ INVESTMENT FUNDS AND ONEANSWER MULTI-ASSET-CLASS FUNDS) (SCH11064) Registered ANZ NEW ZEALAND INVESTMENTS LIMITED
ANZ INVESTMENTS SINGLE-ASSET-CLASS SCHEME (MARKETED AS THE ONEANSWER SINGLE-ASSET-CLASS FUNDS) (SCH11065) Registered ANZ NEW ZEALAND INVESTMENTS LIMITED
ANZ KIWISAVER SCHEME (SCH11062) Registered ANZ NEW ZEALAND INVESTMENTS LIMITED
ONEANSWER KIWISAVER SCHEME (SCH11061) Registered ANZ NEW ZEALAND INVESTMENTS LIMITED
ASB GROUP INVESTMENTS LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
ASB INVESTMENT FUNDS (SCH10685) Registered ASB GROUP INVESTMENTS LIMITED
ASB KIWISAVER SCHEME (SCH10678) Registered ASB GROUP INVESTMENTS LIMITED
BNZ INVESTMENT SERVICES LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
BNZ KIWISAVER SCHEME (SCH10701) Registered BNZ INVESTMENT SERVICES LIMITED
PRIVATE WEALTH SERIES (SCH11384) Registered BNZ INVESTMENT SERVICES LIMITED
YOUWEALTH (SCH12341) Registered BNZ INVESTMENT SERVICES LIMITED
BOOSTER INVESTMENT MANAGEMENT LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
BOOSTER INNOVATION SCHEME (SCH13202) Registered BOOSTER INVESTMENT MANAGEMENT LIMITED
BOOSTER INVESTMENT SCHEME (SCH10844) Registered BOOSTER INVESTMENT MANAGEMENT LIMITED
BOOSTER INVESTMENT SCHEME 2 (SCH12548) Registered BOOSTER INVESTMENT MANAGEMENT LIMITED
BOOSTER KIWISAVER SCHEME (SCH10841) Registered BOOSTER INVESTMENT MANAGEMENT LIMITED
BOOSTER SAVVY SCHEME (SCH13546) Registered BOOSTER INVESTMENT MANAGEMENT LIMITED
BOOSTER SUPERSCHEME (SCH11323) Registered BOOSTER INVESTMENT MANAGEMENT LIMITED
BT FUNDS MANAGEMENT (NZ) LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
WESTPAC ACTIVE SERIES (SCH10564) Registered BT FUNDS MANAGEMENT (NZ) LIMITED
WESTPAC KIWISAVER SCHEME (SCH10585) Registered BT FUNDS MANAGEMENT (NZ) LIMITED
WESTPAC PREMIUM INVESTMENT FUNDS (SCH10817) Registered BT FUNDS MANAGEMENT (NZ) LIMITED
WESTPAC RETIREMENT PLAN (SCH11614) Registered BT FUNDS MANAGEMENT (NZ) LIMITED
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
33 BROADWAY TRUST (SCH11912) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
AIRPARK NOMINEES JOINT VENTURE (SCH11740) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
AUGUSTA KEDRON PARTNERSHIP (SCH12564) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
AUGUSTA ST GEORGES BAY ROAD PROPERTY TRUST (SCH12448) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
BIRCH NOMINEES JOINT VENTURE (SCH11560) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
BRADMAN STREET PROPORTIONATE OWNERSHIP SCHEME (SCH11503) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
BUILDING A GRAHAM STREET LIMITED PARTNERSHIP (SCH10571) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
BUILDING B GRAHAM STREET LIMITED PARTNERSHIP (SCH10922) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
CENTURIA NZ PROPERTY FUND (SCH12900) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
FERNHILL NOMINEES JOINT VENTURE (SCH11564) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
FORMATION ST PROPORTIONATE OWNERSHIP SCHEME (SCH11478) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
HIBISCUS NOMINEES JOINT VENTURES (SCH11466) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
LAMBIE DR PROPERTY SCHEME (SCH11586) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
LINK DR PROPERTY SCHEME (SCH11587) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
MANADON STREET PROPERTY SCHEME (SCH11532) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
PEACHGROVE ROAD LIMITED PARTNERSHIP (SCH11471) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
QUINNS HILL ROAD PARTNERSHIP (SCH10523) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
SHANDS ROAD LIMITED PARTNERSHIP (SCH11468) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
SHERBROOKE RD PARTNERSHIP (SCH11507) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
SIR WILLIAM PICKERING DRIVE LIMITED PARTNERSHIP (SCH12323) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
TAKANINI NOMINEES JOINT VENTURE (SCH11465) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
VICKERS ROAD PROPERTY SCHEME (SCH11556) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
WESTPOINT PROPERTY SCHEME (SCH11602) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
WILLIAMS STREET NOMINEES JOINT VENTURE (SCH11570) Registered CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
FIRST MORTGAGE MANAGERS LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
FIRST MORTGAGE PIE TRUST (SCH10249) Registered FIRST MORTGAGE MANAGERS LIMITED
FIRST MORTGAGE TRUST GROUP INVESTMENT FUND (SCH10239) Registered FIRST MORTGAGE MANAGERS LIMITED
FISHER FUNDS MANAGEMENT LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
FISHER FUNDS INVESTMENT SERIES (SCH10642) Registered FISHER FUNDS MANAGEMENT LIMITED
FISHER FUNDS KIWISAVER SCHEME (SCH10636) Registered FISHER FUNDS MANAGEMENT LIMITED
FISHER FUNDS LIFESAVER PLAN (SCH10637) Registered FISHER FUNDS MANAGEMENT LIMITED
FISHER FUNDS MANAGED FUNDS (SCH10640) Registered FISHER FUNDS MANAGEMENT LIMITED
FISHER FUNDS PREMIUM SERVICE (SCH10641) Registered FISHER FUNDS MANAGEMENT LIMITED
FISHER FUNDS TWO KIWISAVER SCHEME (SCH10597) Registered FISHER FUNDS MANAGEMENT LIMITED
FUTUREPLAN (SCH11318) Registered FISHER FUNDS MANAGEMENT LIMITED
FUNDROCK NZ LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
ACI FUNDS (SCH13499) Registered FUNDROCK NZ LIMITED
ANTIPODES INVESTMENT FUNDS (SCH12434) Registered FUNDROCK NZ LIMITED
APN INVESTMENT FUNDS SCHEME (SCH11734) Registered FUNDROCK NZ LIMITED
AURORA KIWISAVER SCHEME (SCH13055) Registered FUNDROCK NZ LIMITED
BENTHAM INVESTMENT FUNDS (SCH13506) Registered FUNDROCK NZ LIMITED
COLCHESTER INVESTMENT FUNDS (SCH13056) Registered FUNDROCK NZ LIMITED
COOLABAH INVESTMENT FUNDS (SCH13148) Registered FUNDROCK NZ LIMITED
DIMENSIONAL INVESTMENT FUNDS (SCH13317) Registered FUNDROCK NZ LIMITED
FIRST SENTIER INVESTORS (NZ) SCHEME (SCH13089) Registered FUNDROCK NZ LIMITED
FOUNDATION SERIES FUNDS (SCH13175) Registered FUNDROCK NZ LIMITED
FRANKLIN TEMPLETON INVESTMENT FUNDS (SCH12302) Registered FUNDROCK NZ LIMITED
HOBSON WEALTH INVESTMENT FUNDS (SCH12667) Registered FUNDROCK NZ LIMITED
HYPERION INVESTMENT FUNDS (SCH13281) Registered FUNDROCK NZ LIMITED
INVESTNOW KIWISAVER SCHEME (SCH12874) Registered FUNDROCK NZ LIMITED
LIGHTHOUSE INVESTMENT FUNDS (SCH13048) Registered FUNDROCK NZ LIMITED
RUSSELL INVESTMENT FUNDS (SCH10586) Registered FUNDROCK NZ LIMITED
SCHRODER INVESTMENT FUNDS (SCH13639) Registered FUNDROCK NZ LIMITED
SQUIRREL INVESTMENT FUNDS (SCH13142) Registered FUNDROCK NZ LIMITED
STEWART INVESTORS (NZ) MANAGED INVESTMENT SCHEME (SCH13295) Registered FUNDROCK NZ LIMITED
TE AHUMAIRANGI INVESTMENT FUNDS (SCH13146) Registered FUNDROCK NZ LIMITED
VAULT DIGITAL FUNDS (SCH13147) Registered FUNDROCK NZ LIMITED
VISION INVEST NZ FUNDS (SCH12865) Registered FUNDROCK NZ LIMITED
GENERATE INVESTMENT MANAGEMENT LIMITED

Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
GENERATE KIWISAVER SCHEME (SCH10791) Registered GENERATE INVESTMENT MANAGEMENT LIMITED
GENERATE UNIT TRUST SCHEME (SCH12736) Registered GENERATE INVESTMENT MANAGEMENT LIMITED
GOODMAN (NZ) LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
GOODMAN PROPERTY TRUST (SCH11225) Registered GOODMAN (NZ) LIMITED
HARBOUR ASSET MANAGEMENT LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
HARBOUR INVESTMENT FUNDS (SCH10815) Registered HARBOUR ASSET MANAGEMENT LIMITED
HUNTER INVESTMENT FUNDS (SCH11176) Registered HARBOUR ASSET MANAGEMENT LIMITED
KIWI WEALTH INVESTMENTS LIMITED PARTNERSHIP
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
KIWI WEALTH SUPER SCHEME (SCH10814) Registered KIWI WEALTH INVESTMENTS LIMITED PARTNERSHIP
KIWI WEALTH LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
KIWI WEALTH KIWISAVER SCHEME (SCH10713) Registered KIWI WEALTH LIMITED
KIWI WEALTH MANAGED FUNDS (SCH12389) Registered KIWI WEALTH LIMITED
MEDICAL FUNDS MANAGEMENT LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
MAS INVESTMENT FUNDS  (SCH13659) Registered MEDICAL FUNDS MANAGEMENT LIMITED
MAS KIWISAVER SCHEME (SCH10705) Registered MEDICAL FUNDS MANAGEMENT LIMITED
MAS RETIREMENT SAVINGS SCHEME (SCH10706) Registered MEDICAL FUNDS MANAGEMENT LIMITED
MERCER (N.Z.) LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
DEFENCE FORCE SUPERANNUATION SCHEME (SCH11069) Registered MERCER (N.Z.) LIMITED
MERCER FLEXISAVER (SCH10280) Registered MERCER (N.Z.) LIMITED
MERCER INVESTMENT FUNDS (SCH10307) Registered MERCER (N.Z.) LIMITED
MERCER KIWISAVER SCHEME (SCH10245) Registered MERCER (N.Z.) LIMITED
MERCER SUPER TRUST (SCH10697) Registered MERCER (N.Z.) LIMITED
NEW ZEALAND DEFENCE FORCE KIWISAVER SCHEME (SCH10279) Registered MERCER (N.Z.) LIMITED
MILFORD FUNDS LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
MILFORD INVESTMENT FUNDS (SCH10700) Registered MILFORD FUNDS LIMITED
MILFORD KIWISAVER PLAN (SCH10498) Registered MILFORD FUNDS LIMITED
NEW ZEALAND FUNDS MANAGEMENT LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
NZ FUNDS KIWISAVER SCHEME (SCH10783) Registered NEW ZEALAND FUNDS MANAGEMENT LIMITED
NZ FUNDS MANAGED PORTFOLIO SERVICE PART ONE (SCH10786) Registered NEW ZEALAND FUNDS MANAGEMENT LIMITED
NZ FUNDS MANAGED PORTFOLIO SERVICE PART TWO (SCH10803) Registered NEW ZEALAND FUNDS MANAGEMENT LIMITED
NZ FUNDS MANAGED SUPERANNUATION SERVICE (SCH11205) Registered NEW ZEALAND FUNDS MANAGEMENT LIMITED
NIKKO ASSET MANAGEMENT NEW ZEALAND LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
NIKKO AM KIWISAVER SCHEME (SCH12354) Registered NIKKO ASSET MANAGEMENT NEW ZEALAND LIMITED
NIKKO AM NZ INVESTMENT SCHEME (SCH10488) Registered NIKKO ASSET MANAGEMENT NEW ZEALAND LIMITED
NORTHWEST HEALTHCARE PROPERTIES MANAGEMENT LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
VITAL HEALTHCARE PROPERTY TRUST (SCH11214) Registered NORTHWEST HEALTHCARE PROPERTIES MANAGEMENT LIMITED
PIE FUNDS MANAGEMENT LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
JUNO KIWISAVER SCHEME (SCH12451) Registered PIE FUNDS MANAGEMENT LIMITED
PIE FUNDS MANAGEMENT SCHEME (SCH10581) Registered PIE FUNDS MANAGEMENT LIMITED
SIMPLICITY NZ LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
SIMPLICITY INVESTMENT FUNDS (SCH11873) Registered SIMPLICITY NZ LIMITED
SIMPLICITY KIWISAVER SCHEME (SCH10736) Registered SIMPLICITY NZ LIMITED
SMARTSHARES LIMITED
Scheme
. sort ascending
Scheme Status
. sort descending
Reporting Entity
. sort descending
Actions
NZ CORE EQUITY TRUST (SCH10764) Registered SMARTSHARES LIMITED
QUAYSTREET FUNDS (SCH10414) Registered SMARTSHARES LIMITED
QUAYSTREET KIWISAVER SCHEME (SCH10663) Registered SMARTSHARES LIMITED
SELECT KIWISAVER SCHEME (SCH13004) Registered SMARTSHARES LIMITED
SMARTSHARES EXCHANGE TRADED FUNDS (SCH10752) Registered SMARTSHARES LIMITED
SUPERLIFE INVEST (SCH10765) Registered SMARTSHARES LIMITED
SUPERLIFE KIWISAVER SCHEME (SCH10768) Registered SMARTSHARES LIMITED
SUPERLIFE SUPERANNUATION MASTER TRUST (SCH10688) Registered SMARTSHARES LIMITED
SUPERLIFE UK PENSION TRANSFER SCHEME (SCH10767) Registered SMARTSHARES LIMITED
SUPERLIFE WORKPLACE SAVINGS SCHEME (SCH10769) Registered SMARTSHARES LIMITED

In [28]:
table_final = pd.read_csv(f'{folder}/table_details_final_scheme.csv') 
links_scheme_final = pd.DataFrame()
for index, row in table_final.iterrows():
    firm_name = row['Company Name']
    links = [masterlink + link for link in ast.literal_eval(row.Link)]
    # Create a list of dictionaries containing the data
    data = [{'Scheme Name': row['Scheme'], 'CRE Name': row['Company Name'], 'Link': link} for link in links]
    # Create the DataFrame
    df = pd.DataFrame(data)    
    links_scheme_final = pd.concat([links_scheme_final, df],ignore_index = True)
links_scheme_final.head(5)
links_scheme_final.to_csv(f'{folder}/links_scheme_final.csv')

links_scheme_final = pd.read_csv(f'{folder}/links_scheme_final.csv')
# extract  data 
table_details_final_scheme_detail = pd.DataFrame()

for index, row in links_scheme_final.iterrows():
    firm_name = row['CRE Name']
    print(firm_name)
    link = row.Link

    # open the browser to activate the process using the URL defined 
    driver.get(link)
    
    time.sleep(3)
       
    # Wait for the table to become visible
    table = WebDriverWait(driver, 30).until(
        EC.visibility_of_element_located((By.CSS_SELECTOR, "table"))
    )
    
    text = table.text
    print(text)
    # Create a dictionary with the row data
    row_data = pd.DataFrame([{
        'Link': link,
        'Company Name': firm_name,
        'Text': text
    }])
    # After obtaining the table, you can perform any further actions required
    table_details_final_scheme_detail = pd.concat([table_details_final_scheme_detail, row_data], ignore_index=True)

table_details_final_scheme_detail.to_csv(f'{folder}/table_details_final.scheme_detail.csv')

AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
ANZ INVESTMENT SERVICES (NEW ZEALAND) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
ANZ NEW ZEALAND INVESTMENTS LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
ANZ NEW ZEALAND INVESTMENTS LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
ANZ NEW ZEALAND INVESTMENTS LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
ANZ NEW ZEALAND INVESTMENTS LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
ANZ NEW ZEALAND INVESTMENTS LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
ASB GROUP INVESTMENTS LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
ASB GROUP INVESTMENTS LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
BNZ INVESTMENT SERVICES LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
BNZ INVESTMENT SERVICES LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
BNZ INVESTMENT SERVICES LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
BOOSTER INVESTMENT MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
BOOSTER INVESTMENT MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
BOOSTER INVESTMENT MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
BOOSTER INVESTMENT MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
BOOSTER INVESTMENT MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
BOOSTER INVESTMENT MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
BT FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
BT FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
BT FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
BT FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
CENTURIA FUNDS MANAGEMENT (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FIRST MORTGAGE MANAGERS LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FIRST MORTGAGE MANAGERS LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FISHER FUNDS MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FISHER FUNDS MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FISHER FUNDS MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FISHER FUNDS MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FISHER FUNDS MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FISHER FUNDS MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FISHER FUNDS MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED

Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
FUNDROCK NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
GENERATE INVESTMENT MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
GENERATE INVESTMENT MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
GOODMAN (NZ) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
HARBOUR ASSET MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
HARBOUR ASSET MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
KIWI WEALTH INVESTMENTS LIMITED PARTNERSHIP
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
KIWI WEALTH LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
KIWI WEALTH LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
MEDICAL FUNDS MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
MEDICAL FUNDS MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
MEDICAL FUNDS MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
MERCER (N.Z.) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
MERCER (N.Z.) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
MERCER (N.Z.) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
MERCER (N.Z.) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
MERCER (N.Z.) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
MERCER (N.Z.) LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
MILFORD FUNDS LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
MILFORD FUNDS LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
NEW ZEALAND FUNDS MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
NEW ZEALAND FUNDS MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
NEW ZEALAND FUNDS MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
NEW ZEALAND FUNDS MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
NIKKO ASSET MANAGEMENT NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
NIKKO ASSET MANAGEMENT NEW ZEALAND LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
NORTHWEST HEALTHCARE PROPERTIES MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
There are no records to display.
PIE FUNDS MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
PIE FUNDS MANAGEMENT LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
SIMPLICITY NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
SIMPLICITY NZ LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
SMARTSHARES LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
SMARTSHARES LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
SMARTSHARES LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
SMARTSHARES LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
SMARTSHARES LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
SMARTSHARES LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
SMARTSHARES LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
SMARTSHARES LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
SMARTSHARES LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024
SMARTSHARES LIMITED
Reporting Period
. sort descending
Actions
31-03-2024 - Due by 31-07-2024

In [29]:
links_scheme_final =pd.read_csv(f'{folder}/links_scheme_final.csv')

# Clean up the 'Text' column
table_details_final_scheme_detail['text_new'] = table_details_final_scheme_detail['Text'].str.replace('\n', '|') \
                                                              .str.replace('Reporting Period', '') \
                                                              .str.replace('. sort descending', '') \
                                                              .str.replace('. sort ascending', '') \
                                                              .str.replace('Scheme', '')\
                                                              .str.replace('Scheme Status', '')\
                                                              .str.replace('Reporting Entity', '')\
                                                              .str.replace('Status', '')\
                                                              .str.replace('Registered', '_')\
                                                   .str.replace('Actions', '')\



table_details_final_scheme_detail = pd.merge(table_details_final_scheme_detail, 
                                            links_scheme_final[['Link','Scheme Name']],
                                            how = 'left',
                                            left_on = 'Link',
                                            right_on = 'Link')
# Display the DataFrame
print(table_details_final_scheme_detail.head(5))
table_details_final_scheme_detail.to_csv(f'{folder}/table_details_final.scheme_detail.new.csv')

                                                Link  \
0  https://crd-app.companiesoffice.govt.nz/dashbo...
1  https://crd-app.companiesoffice.govt.nz/dashbo...
2  https://crd-app.companiesoffice.govt.nz/dashbo...
3  https://crd-app.companiesoffice.govt.nz/dashbo...
4  https://crd-app.companiesoffice.govt.nz/dashbo...

                                Company Name  \
0  AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
1  AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
2  AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
3  AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED
4  AMP WEALTH MANAGEMENT NEW ZEALAND LIMITED

                                                Text  \
0  Reporting Period\n. sort descending\nActions\n...
1  Reporting Period\n. sort descending\nActions\n...
2  Reporting Period\n. sort descending\nActions\n...
3  Reporting Period\n. sort descending\nActions\n...
4  Reporting Period\n. sort descending\nActions\n...

                            text_new  \
0  |||31-03-2024 - Due by 31-07-2024
1  |||31-03-2024 - Due by 31-07-2024
2  |||31-03-2024 - Due by 31-07-2024
3  |||31-03-2024 - Due by 31-07-2024
4  |||31-03-2024 - Due by 31-07-2024

                                         Scheme Name
0                    AMP INVESTMENT TRUST (SCH10721)
1                    AMP KIWISAVER SCHEME (SCH10367)
2                       AMP MANAGED FUNDS (SCH13265)
3  AMP PASSIVE PERSONAL RETIREMENT PLAN - INTERNA...
4  AMP PASSIVE PERSONAL RETIREMENT PLAN - NEW ZEA...

In [30]:
table_details_final =pd.read_csv(f'{folder}/table_details_final.new.csv') 
table_details_final_scheme_detail =pd.read_csv(f'{folder}/table_details_final.scheme_detail.new.csv') 
table_details_final_noscheme = table_details_final[table_details_final['Text'].str.contains('Scheme', case=False) == False]
table_details_final_noscheme = pd.concat([table_details_final_noscheme,
                                          table_details_final_scheme_detail],ignore_index = True)
table_details_final_noscheme.drop(columns =['Unnamed: 0.1','Unnamed: 0'],inplace=True)
table_details_final_noscheme.head(5)
table_details_final_noscheme['text_new'] = table_details_final_noscheme['text_new'].str.replace('|', '') 
# Set 'status' column based on conditions
table_details_final_noscheme['status'] = np.where(
    table_details_final_noscheme['text_new'].str.contains('no records', case=False),
    'No records',
    ''
)

table_details_final_noscheme['status'] = np.where(
    table_details_final_noscheme['text_new'].str.contains('Due ', case=False),
    'Have records but not submitted',
    table_details_final_noscheme['status']
)


table_details_final_noscheme['status'] = np.where(
    table_details_final_noscheme['text_new'].str.contains('Click to view Climate Statement', case=False),
    'Have records and have submitted',
    table_details_final_noscheme['status']
)


print(table_details_final_noscheme['status'].value_counts())

# Set 'status' column based on scheme 
table_details_final_noscheme['scheme'] = np.where(
    table_details_final_noscheme['Scheme Name'].isnull()==True,
    'Company',
    'Investment Scheme'
)

print(table_details_final_noscheme['scheme'].value_counts())
# Custom function to split date strings
def split_dates(date_str):
    if " - Due by " in date_str:
        due_date, submit_date = date_str.split(" - Due by ")
        return due_date, submit_date
    else:
        return "0", "0"

# Apply the function to each row of the DataFrame
table_details_final_noscheme[['Due Date', 'Submit Date']] = table_details_final_noscheme['text_new'].apply(lambda x: pd.Series(split_dates(x)))

# Print the modified DataFrame
print(table_details_final_noscheme.head(5))
table_details_final_noscheme.to_csv(f'{folder}/table_details_final_noscheme.final.csv')

status
Have records but not submitted     151
No records                          77
Have records and have submitted     30
Name: count, dtype: int64
scheme
Company              135
Investment Scheme    123
Name: count, dtype: int64
                                                Link  \
0  https://crd-app.companiesoffice.govt.nz/dashbo...
1  https://crd-app.companiesoffice.govt.nz/dashbo...
2  https://crd-app.companiesoffice.govt.nz/dashbo...
3  https://crd-app.companiesoffice.govt.nz/dashbo...
4  https://crd-app.companiesoffice.govt.nz/dashbo...

                  Company Name  \
0         AA INSURANCE LIMITED
1  AFT PHARMACEUTICALS LIMITED
2      AIA NEW ZEALAND LIMITED
3      AIR NEW ZEALAND LIMITED
4    ARBORGEN HOLDINGS LIMITED

                                                Text  \
0  Reporting Period\n. sort descending\nActions\n...
1  Reporting Period\n. sort descending\nActions\n...
2  Reporting Period\n. sort descending\nActions\n...
3  Reporting Period\n. sort descending\nActions\n...
4  Reporting Period\n. sort descending\nActions\n...

                                         text_new Scheme Name  \
0                There are no records to display.         NaN
1                  31-03-2024 - Due by 31-07-2024         NaN
2  31-12-2023 - Click to view Climate Statement/s         NaN
3                There are no records to display.         NaN
4                  31-03-2024 - Due by 31-07-2024         NaN

                            status   scheme    Due Date Submit Date
0                       No records  Company           0           0
1   Have records but not submitted  Company  31-03-2024  31-07-2024
2  Have records and have submitted  Company           0           0
3                       No records  Company           0           0
4   Have records but not submitted  Company  31-03-2024  31-07-2024

In [31]:
table_details_final = pd.read_csv(f'{folder}/table_details_final_noscheme.final.csv') 

#Get the disclose list:
# Search for rows containing 'scheme' in the 'Text' column
disclose_rows = table_details_final[table_details_final['status'] =='Have records and have submitted']

print(disclose_rows.shape)
# Display the rows containing 'scheme'
disclose_rows.head(5)

(30, 10)

,Unnamed: 0,Link,Company Name,Text,text_new,Scheme Name,status,scheme,Due Date,Submit Date
2,2,https://crd-app.companiesoffice.govt.nz/dashbo...,AIA NEW ZEALAND LIMITED,Reporting Period\n. sort descending\nActions\n...,31-12-2023 - Click to view Climate Statement/s,NaN,Have records and have submitted,Company,0,0
13,13,https://crd-app.companiesoffice.govt.nz/dashbo...,BANK OF CHINA (NEW ZEALAND) LIMITED,Reporting Period\n. sort descending\nActions\n...,31-12-2023 - Click to view Climate Statement/s,NaN,Have records and have submitted,Company,0,0
16,16,https://crd-app.companiesoffice.govt.nz/dashbo...,BRISCOE GROUP LIMITED,Reporting Period\n. sort descending\nActions\n...,31-01-2024 - Click to view Climate Statement/s,NaN,Have records and have submitted,Company,0,0
17,17,https://crd-app.companiesoffice.govt.nz/dashbo...,CDL INVESTMENTS NEW ZEALAND LIMITED,Reporting Period\n. sort descending\nActions\n...,31-12-2023 - Click to view Climate Statement/s,NaN,Have records and have submitted,Company,0,0
18,18,https://crd-app.companiesoffice.govt.nz/dashbo...,CHANNEL INFRASTRUCTURE NZ LIMITED,Reporting Period\n. sort descending\nActions\n...,31-12-2023 - Click to view Climate Statement/s,NaN,Have records and have submitted,Company,0,0

In [457]:
# extract  data 
for index, row in disclose_rows.head(1).iterrows():
    firm_name = row['Company Name']
    print(firm_name)
    link = row.Link

    # open the browser to activate the process using the URL defined 
    driver.get(link)
    time.sleep(3)
           
    # Wait for the table to become visible
    table = WebDriverWait(driver, 30).until(
        EC.visibility_of_element_located((By.CSS_SELECTOR, "table"))
    )
    
    text = table.text
    print(text)
    
    # Get the table HTML
    table_html = table.get_attribute("outerHTML")
    #Extract table data
    # Parse the HTML table content with BeautifulSoup
    soup = BeautifulSoup(table_html, 'html.parser')
    
    rows = soup.find_all('tr')

    # Initialize lists to store table data and associated links
    table_data = []

    # Loop through table rows
    for row in rows[1:]:
        print(row.text)
        # Extract table cells (columns)
        cells = row.find_all(['td'])
        row_data = []
        for cell in cells:
            # Extract text from cell
            cell_text = cell.get_text(strip=True)
            row_data.append(cell_text)
        links = []
        # Check if cell contains a link
        new_link = cell.find('a')
        if new_link:
            # Extract link URL
            new_link.click()

BRISCOE GROUP LIMITED
Reporting Period
. sort descending
Actions
31-01-2024 - Click to view Climate Statement/s

Reporting Period. sort descendingActions31-01-2024 - Click to view Climate Statement/s View detailsThere are no records to display.You don't have permissions to view these records.Error completing request.  Loading... Create×Close Edit×Close View details×Close Delete×CloseAre you sure you want to delete this record?DeleteCancel Error×CloseWe're sorry, an error has occurred.Close


Reporting Period. sort descendingActions
31-01-2024 - Click to view Climate Statement/s View details

TypeError: 'NoneType' object is not callable